### PR TITLE
"Invite student" popup enhancements

### LINKED ISSUE #10: Add share link in "add student" menu
When you hit add student the first option is to invite via share link. This is currently just a static link that doesn't work. It should be the same link as the class (the URL on top of the page)

### PR DESCRIPTION
**Pull request by shybovycha**
* Added "readonly" attribute for sharelink input so that it cannot be edited by a user
* Added notification after the link has been copied to a clip-buffer

Both relate and resolve #10

### CODE REVIEW

File: src/components/addstudent.tsx [hunk 1]
```diff
@@ -1,25 +1,34 @@
...
+            isModalOpen: false,
+            showLinkCopiedMessage: false
         };
     }
 
     copyCourseLink() {
+        const timeoutLength = 5 * 1000;
+        this.setState({ showLinkCopiedMessage: true });
+
+        setTimeout(() => {
```
Comment (sammysamau) [inline src/components/addstudent.tsx:28]: use requestAnimationFrame instead
see [here](https://stackoverflow.com/questions/38709923/why-is-requestanimationframe-better-than-setinterval-or-settimeout) why it's better

**Review by sammysamau — APPROVED** [review]

File: src/components/addstudent.tsx (hunk 1 above)
Comment (shybovycha) [reply src/components/addstudent.tsx:28]: Yeah, but this code does not have an intent to animate things (what's more important - *manually* animate). Thus I believe `requestAnimationFrame` is a bad candidate here...

**Comment by sammysamau** [comment]
Thanks!
